"use client";

import { useState, useTransition } from "react";
import { Check, ChevronLeft, ChevronRight, FileUp, Info, Loader2, ShieldCheck } from "lucide-react";
import { CanvasAssinatura } from "@/components/canvas-assinatura";
import { createClient } from "@/lib/supabase/client";
import { confirmarUpload, finalizarFicha, prepararUpload, salvarRascunho } from "./actions";

type Dados = Record<string, string | number | boolean | null>;
type Documento = { id: string; nome_arquivo: string; tipo: string };
const CAMPO = "mt-1.5 w-full rounded-lg border border-stone-300 bg-white px-3 py-2.5 text-sm text-stone-900 outline-none transition focus:border-[#731515] focus:ring-2 focus:ring-[#731515]/10";
const ETAPAS = ["Proposta", "Dados pessoais", "Renda e patrimônio", "Documentos", "Declaração"];

const GARANTIAS = [
  { nome: "Seguro Fiança", itens: ["Exige cartão de crédito com limite mínimo de 3 vezes o aluguel.", "Taxa de adesão de R$ 150,00, parcelável em 2 ou 3 vezes.", "Custo a partir de 11% do pacote mensal, multiplicado por 12 meses.", "Renovação anual e sem reembolso ao final da locação."], obs: "A taxa de 11% é mínima e pode aumentar após a análise interna da seguradora." },
  { nome: "Título de Capitalização", itens: ["Aplicação entre 6 e 10 vezes o pacote mensal, conforme análise.", "Rendimento pela TR, com possível deságio no resgate antes de 12 meses.", "Pagamento à vista ou em até 18 vezes com juros não reembolsáveis.", "Ao final, o valor aplicado e os rendimentos podem ser resgatados." ] },
  { nome: "Garantia Investe", itens: ["Investimento entre 6 e 10 vezes o pacote mensal na Warren.", "Rendimento pela SELIC, com possível deságio no resgate antes de 12 meses.", "Ao final, o cliente pode resgatar o saldo ou manter a conta de investimentos." ] },
  { nome: "Fiador", itens: ["Deve comprovar renda suficiente e apresentar documentação pessoal e financeira.", "Para garantia com imóvel, o bem deve estar quitado e livre para análise.", "É necessária escritura e certidão de ônus emitida há no máximo 30 dias."], obs: "O fiador também passa por análise cadastral. A indicação não garante aprovação." },
];

const DOCS_BASE = ["CPF e RG", "Certidão de nascimento, casamento ou divórcio", "Comprovante de residência atualizado", "3 últimos comprovantes de renda", "Imposto de renda e recibo da declaração"];
const ANEXOS_BASE = ["Documento de identidade", "Certidão de estado civil", "Comprovante de residência", "Comprovantes de renda — 3 últimos", "Imposto de renda e recibo", "Documentos profissionais / complementares", "Outros documentos"];

function mascaraCpf(v: string) { return v.replace(/\D/g, "").slice(0, 11).replace(/(\d{3})(\d)/, "$1.$2").replace(/(\d{3})(\d)/, "$1.$2").replace(/(\d{3})(\d{1,2})$/, "$1-$2"); }
function mascaraTelefone(v: string) { const d = v.replace(/\D/g, "").slice(0, 11); return d.length > 10 ? d.replace(/(\d{2})(\d{5})(\d{4})/, "($1) $2-$3") : d.replace(/(\d{2})(\d{4})(\d{0,4})/, "($1) $2-$3"); }
function mascaraCep(v: string) { return v.replace(/\D/g, "").slice(0, 8).replace(/(\d{5})(\d)/, "$1-$2"); }
function mascaraMoeda(v: string) { const n = Number(v.replace(/\D/g, "")) / 100; return n ? n.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) : ""; }

export function FormularioFicha({ token, iniciais, documentosIniciais }: { token: string; iniciais: Dados; documentosIniciais: Documento[] }) {
  const [etapa, setEtapa] = useState(0), [dados, setDados] = useState<Dados>(iniciais);
  const [documentos, setDocumentos] = useState(documentosIniciais), [assinatura, setAssinatura] = useState<string | null>(null);
  const [mensagem, setMensagem] = useState(""), [enviandoArquivo, setEnviandoArquivo] = useState(false);
  const [pendente, iniciar] = useTransition();
  const garantia = String(dados.garantia ?? "");
  const temFiador = garantia === "Fiador";

  function atualizar(nome: string, valor: string | boolean) { setDados((atual) => ({ ...atual, [nome]: valor })); }
  function input(nome: string, rotulo: string, obrigatorio = false, tipo = "text", mascara?: (v: string) => string) { return <label className="block text-sm font-medium text-stone-700">{rotulo}{obrigatorio && <span className="text-[#731515]"> *</span>}<input className={CAMPO} type={tipo} required={obrigatorio} value={String(dados[nome] ?? "")} onChange={(e) => atualizar(nome, mascara ? mascara(e.target.value) : e.target.value)} /></label>; }
  function select(nome: string, rotulo: string, opcoes: string[], obrigatorio = false) { return <label className="block text-sm font-medium text-stone-700">{rotulo}{obrigatorio && <span className="text-[#731515]"> *</span>}<select className={CAMPO} required={obrigatorio} value={String(dados[nome] ?? "")} onChange={(e) => atualizar(nome, e.target.value)}><option value="">Selecione</option>{opcoes.map((o) => <option key={o}>{o}</option>)}</select></label>; }
  function salvarEIr(proxima: number) { setMensagem(""); iniciar(async () => { const r = await salvarRascunho(token, dados); if (!r.ok) setMensagem(r.erro ?? "Não foi possível salvar."); else { setEtapa(proxima); window.scrollTo({ top: 0, behavior: "smooth" }); } }); }
  async function enviarArquivo(file: File, tipo: string) { setMensagem(""); setEnviandoArquivo(true); try { const p = await prepararUpload(token, file.name, file.type, file.size); if (!p.ok || !p.caminho || !p.uploadToken) throw new Error(p.erro); const { error } = await createClient().storage.from("fichas-locacao").uploadToSignedUrl(p.caminho, p.uploadToken, file, { contentType: file.type }); if (error) throw error; const c = await confirmarUpload(token, { caminho: p.caminho, nome: file.name, mime: file.type, tamanho: file.size, tipo }); if (!c.ok) throw new Error(c.erro); setDocumentos((a) => [...a, { id: p.caminho!, nome_arquivo: file.name, tipo }]); } catch (e) { setMensagem(e instanceof Error ? e.message : "Não foi possível enviar o arquivo."); } finally { setEnviandoArquivo(false); } }
  async function enviarArquivos(files: FileList | null, tipo: string) {
    if (!files) return;
    const vagas = 10 - documentos.length;
    if (vagas <= 0) { setMensagem("O limite de 10 arquivos já foi atingido."); return; }
    const selecionados = Array.from(files);
    if (selecionados.length > vagas) setMensagem(`Você pode enviar somente mais ${vagas} arquivo${vagas === 1 ? "" : "s"}.`);
    for (const file of selecionados.slice(0, vagas)) await enviarArquivo(file, tipo);
  }
  function concluir() { setMensagem(""); iniciar(async () => { const r = await finalizarFicha(token, dados, assinatura ?? ""); if (!r.ok) setMensagem(r.erro ?? "Não foi possível enviar."); else window.location.reload(); }); }

  const anexos = [...ANEXOS_BASE];
  if (garantia === "Seguro Fiança") anexos.splice(5, 0, "Última fatura do cartão de crédito");
  if (["Título de Capitalização", "Garantia Investe"].includes(garantia)) anexos.splice(5, 0, "6 últimos contracheques", "6 últimas movimentações bancárias");
  if (temFiador) anexos.splice(5, 0, "Documentos pessoais do fiador", "Comprovantes de renda do fiador", "Escritura e certidão de ônus do imóvel do fiador");

  return <div className="space-y-5">
    <div className="overflow-x-auto"><div className="flex min-w-[560px] items-center">{ETAPAS.map((nome, i) => <div key={nome} className="flex flex-1 items-center last:flex-none"><div className="flex flex-col items-center gap-1"><div className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${i < etapa ? "bg-emerald-600 text-white" : i === etapa ? "bg-[#731515] text-white" : "bg-stone-200 text-stone-500"}`}>{i < etapa ? <Check className="h-4 w-4" /> : i + 1}</div><span className={`whitespace-nowrap text-[11px] ${i === etapa ? "font-semibold text-[#731515]" : "text-stone-500"}`}>{nome}</span></div>{i < 4 && <div className={`mx-2 mb-5 h-px flex-1 ${i < etapa ? "bg-emerald-500" : "bg-stone-200"}`} />}</div>)}</div></div>
    <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm sm:p-7">
      {etapa === 0 && <div className="space-y-6"><div><h2 className="text-xl font-bold">Informações da locação</h2><p className="mt-1 text-sm text-stone-500">Confirme o imóvel e escolha a garantia mais adequada.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2">{input("imovel_interesse", "Imóvel de interesse", true)}</div>{select("finalidade", "Finalidade", ["Residencial", "Comercial"], true)}{select("garantia", "Modalidade de garantia", [...GARANTIAS.map((g) => g.nome), "A definir"], true)}{input("moradores", "Quantas pessoas ocuparão o imóvel?")}{select("possui_pet", "Possui animais?", ["Não", "Sim — pequeno porte", "Sim — médio/grande porte"])}<div className="sm:col-span-2">{input("data_pretendida", "Data pretendida para início", false, "date")}</div></div>
        <div><h3 className="mb-3 text-sm font-bold uppercase tracking-wide text-stone-500">Entenda as garantias</h3><div className="grid gap-3 sm:grid-cols-2">{GARANTIAS.map((g) => <details key={g.nome} open={garantia === g.nome} className={`rounded-xl border p-4 ${garantia === g.nome ? "border-[#b9822c] bg-amber-50/50" : "border-stone-200"}`}><summary className="cursor-pointer font-semibold text-stone-900">{g.nome}</summary><ul className="mt-3 list-disc space-y-1.5 pl-5 text-xs leading-5 text-stone-600">{g.itens.map((item) => <li key={item}>{item}</li>)}</ul>{g.obs && <p className="mt-3 rounded-lg bg-white/80 p-2 text-xs font-medium text-stone-600"><Info className="mr-1 inline h-3.5 w-3.5" />{g.obs}</p>}</details>)}</div></div>
        <div className="rounded-xl border border-stone-200 bg-stone-50 p-4"><h3 className="flex items-center gap-2 font-semibold"><FileUp className="h-4 w-4 text-[#b9822c]" /> Documentação necessária</h3><ol className="mt-3 list-decimal space-y-1.5 pl-5 text-sm text-stone-600">{DOCS_BASE.map((d) => <li key={d}>{d}</li>)}<li>{garantia === "Seguro Fiança" ? "Última fatura do cartão comprovando o limite disponível." : "Documentos adicionais conforme a garantia escolhida."}</li></ol><p className="mt-3 text-xs leading-5 text-stone-500">Empresário: contrato social, alterações, extratos PJ, IR, pró-labore e DECORE. Pensionista ou aposentado: extratos e comprovantes do benefício. A lista completa aparecerá na etapa de documentos.</p></div>
        <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><ShieldCheck className="mr-1 inline h-4 w-4" />Todas as fichas passam por análise minuciosa. Em caso de recusa, o motivo pode não ser informado pela seguradora em razão das diretrizes da LGPD.</div></div>}

      {etapa === 1 && <div className="space-y-5"><div><h2 className="text-xl font-bold">Dados pessoais</h2><p className="mt-1 text-sm text-stone-500">Preencha exatamente como consta nos documentos.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2">{input("nome_completo", "Nome completo", true)}</div>{input("cpf", "CPF", true, "text", mascaraCpf)}{input("rg", "RG / órgão expedidor", true)}{input("nascimento", "Data de nascimento", true, "date")}{select("estado_civil", "Estado civil", ["Solteiro(a)", "Casado(a)", "União estável", "Divorciado(a)", "Viúvo(a)"], true)}{input("telefone", "Telefone", true, "tel", mascaraTelefone)}{input("email", "E-mail", true, "email")}<div className="sm:col-span-2">{input("endereco", "Endereço residencial atual", true)}</div>{input("cidade", "Cidade / UF", true)}{input("cep", "CEP", true, "text", mascaraCep)}{["Casado(a)", "União estável"].includes(String(dados.estado_civil)) && <><div className="sm:col-span-2 mt-2 border-t border-stone-200 pt-4"><h3 className="font-semibold">Dados do cônjuge</h3></div>{input("conjuge_nome", "Nome completo do cônjuge", true)}{input("conjuge_cpf", "CPF do cônjuge", true, "text", mascaraCpf)}</>}</div></div>}

      {etapa === 2 && <div className="space-y-5"><div><h2 className="text-xl font-bold">Renda e patrimônio</h2><p className="mt-1 text-sm text-stone-500">Informações utilizadas exclusivamente na análise cadastral.</p></div><div className="grid gap-4 sm:grid-cols-2">{input("profissao", "Profissão", true)}{select("tipo_renda", "Tipo de renda", ["Assalariado(a)", "Empresário(a)", "Autônomo(a)", "Aposentado(a)", "Pensionista"], true)}{input("empresa", "Empresa / empregador", true)}{input("renda_mensal", "Renda mensal", true, "text", mascaraMoeda)}{input("tempo_empresa", "Tempo na empresa / atividade")}{select("imovel_proprio", "Possui imóvel?", ["Não", "Sim — quitado", "Sim — financiado"])}{input("veiculo", "Veículo (modelo/ano)")}{input("banco", "Banco principal")}{input("agencia", "Agência")}{input("conta", "Conta")}{input("referencia_nome", "Referência pessoal")}{input("referencia_telefone", "Telefone da referência", false, "tel", mascaraTelefone)}</div>{temFiador && <div className="rounded-xl border border-[#b9822c]/40 bg-amber-50/50 p-4 sm:p-5"><h3 className="text-lg font-bold">Dados do fiador</h3><p className="mt-1 text-xs leading-5 text-stone-600">O fiador deverá comprovar renda e, quando utilizar imóvel como garantia, apresentar escritura e certidão de ônus atualizada, emitida há no máximo 30 dias.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2">{input("fiador_nome", "Nome completo do fiador", true)}</div>{input("fiador_cpf", "CPF do fiador", true, "text", mascaraCpf)}{input("fiador_rg", "RG do fiador", true)}{input("fiador_telefone", "Telefone do fiador", true, "tel", mascaraTelefone)}{input("fiador_email", "E-mail do fiador", true, "email")}<div className="sm:col-span-2">{input("fiador_endereco", "Endereço do fiador", true)}</div>{input("fiador_profissao", "Profissão do fiador", true)}{input("fiador_renda", "Renda mensal do fiador", true, "text", mascaraMoeda)}{select("fiador_imovel_quitado", "Possui imóvel quitado?", ["Sim", "Não"], true)}{input("fiador_imovel", "Identificação do imóvel do fiador")}</div></div>}<label className="block text-sm font-medium text-stone-700">Observações<textarea className={`${CAMPO} min-h-24`} value={String(dados.observacoes ?? "")} onChange={(e) => atualizar("observacoes", e.target.value)} /></label></div>}

      {etapa === 3 && <div className="space-y-5"><div><h2 className="text-xl font-bold">Documentos</h2><p className="mt-1 text-sm text-stone-500">Envie todos os documentos aplicáveis. É possível selecionar vários arquivos, respeitando o limite total de 10.</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-[#731515] transition-all" style={{ width: `${Math.min(100, documentos.length * 10)}%` }} /></div><p className="mt-1 text-right text-xs font-medium text-stone-500">{documentos.length} de 10 arquivos</p></div><div className="grid gap-3 sm:grid-cols-2">{anexos.map((tipo) => <label key={tipo} className={`flex items-center gap-3 rounded-xl border border-dashed border-stone-300 p-4 ${documentos.length >= 10 ? "cursor-not-allowed opacity-50" : "cursor-pointer hover:border-[#731515]"}`}><FileUp className="h-5 w-5 shrink-0 text-[#b9822c]" /><span className="flex-1 text-sm font-medium">{tipo}</span><input type="file" multiple className="sr-only" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={enviandoArquivo || documentos.length >= 10} onChange={(e) => { void enviarArquivos(e.target.files, tipo); e.target.value = ""; }} /></label>)}</div>{enviandoArquivo && <p className="flex items-center gap-2 text-sm text-stone-500"><Loader2 className="h-4 w-4 animate-spin" /> Enviando documento…</p>}{documentos.length > 0 && <div className="rounded-xl bg-stone-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-stone-500">Arquivos enviados ({documentos.length}/10)</p><ul className="mt-2 space-y-1">{documentos.map((d) => <li key={d.id} className="text-sm text-stone-700">✓ {d.nome_arquivo} <span className="text-xs text-stone-400">({d.tipo})</span></li>)}</ul></div>}<div className="rounded-xl border border-stone-200 p-4 text-xs leading-5 text-stone-600"><strong>Conforme a ocupação:</strong> empresário — contrato social, alterações, extratos PJ, IR, pró-labore e DECORE; pensionista — extrato, crédito da pensão e contracheque; aposentado — extrato, crédito INSS e comprovante do benefício.</div></div>}

      {etapa === 4 && <div className="space-y-5"><div><h2 className="text-xl font-bold">Declaração, LGPD e assinatura</h2><p className="mt-1 text-sm text-stone-500">Leia as condições antes do envio definitivo.</p></div><div className="space-y-3 rounded-xl bg-stone-50 p-4 text-sm leading-6 text-stone-600"><p><strong>Veracidade:</strong> declaro que as informações prestadas e os documentos enviados são verdadeiros e estou ciente de que o envio não representa aprovação automática da locação.</p><p><strong>Finalidade:</strong> autorizo o tratamento dos dados para análise cadastral, avaliação da garantia, elaboração e execução do contrato de locação.</p><p><strong>Compartilhamento:</strong> os dados poderão ser compartilhados, no limite necessário, com proprietários, seguradoras, plataformas de garantia, prestadores de análise e parceiros envolvidos na operação.</p><p><strong>Armazenamento e segurança:</strong> os dados e documentos serão mantidos em ambiente de acesso restrito pelo período necessário ao processo e ao cumprimento de obrigações legais e regulatórias.</p><p><strong>Direitos do titular:</strong> posso solicitar confirmação, acesso, correção e demais direitos previstos na Lei nº 13.709/2018, observadas as hipóteses legais de conservação.</p></div><label className="flex items-start gap-3 rounded-xl border border-stone-200 p-4 text-sm"><input type="checkbox" className="mt-1 accent-[#731515]" checked={dados.consentimento_lgpd === true} onChange={(e) => atualizar("consentimento_lgpd", e.target.checked)} /><span>Li as cláusulas acima e autorizo o tratamento dos meus dados pessoais e documentos para as finalidades informadas, nos termos da LGPD.</span></label><div><p className="mb-2 text-sm font-semibold">Assinatura do proponente *</p><CanvasAssinatura onChange={setAssinatura} /></div></div>}
      {mensagem && <p className="mt-5 rounded-lg bg-rose-50 px-4 py-3 text-sm text-rose-700">{mensagem}</p>}
      <div className="mt-7 flex items-center justify-between border-t border-stone-200 pt-5"><button type="button" disabled={etapa === 0 || pendente} onClick={() => setEtapa((e) => e - 1)} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-sm font-semibold text-stone-600 disabled:invisible"><ChevronLeft className="h-4 w-4" /> Voltar</button>{etapa < 4 ? <button type="button" disabled={pendente || enviandoArquivo} onClick={() => salvarEIr(etapa + 1)} className="inline-flex items-center gap-2 rounded-lg bg-[#731515] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{pendente && <Loader2 className="h-4 w-4 animate-spin" />} Salvar e continuar <ChevronRight className="h-4 w-4" /></button> : <button type="button" disabled={pendente} onClick={concluir} className="inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{pendente && <Loader2 className="h-4 w-4 animate-spin" />} Enviar ficha</button>}</div>
    </section><p className="text-center text-xs text-stone-500">O progresso é salvo ao avançar. Você pode fechar esta página e continuar usando o mesmo link.</p>
  </div>;
}
